# Generated by Django 3.1.4 on 2022-05-22 12:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='image',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to=accounts.models.filepath),
        ),
        migrations.AlterField(
            model_name='add',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add',
            name='profession',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
